theme = "hugo-awesome-identity-darkmode"
baseURL = "https://Coniass.com"
title = "Coniass - Hobby Nerd / IT Student"
languageCode = "en-US"
# Content without language indicator will default to this language
defaultContentLanguage = "en"
# Make .Summary and .WordCount behave correctly for CJK languages
hasCJKLanguage = true
PygmentsCodeFences = true
# Enable to turn relative URLs into absolute
canonifyURLs = true
# Do not convert the url/path to lowercase
disablePathToLower = false
# Enable Emoji emoticons support for page content
enableEmoji = true
# Update the `Lastmod` parameter for each page using the last git commit date for that content file
enableGitInfo = true
# Enable generation of `robots.txt` file
enableRobotsTXT = true

# Google Analytics tracking ID
googleAnalytics = "G-HQKMYZB24J"

## Meta Configurations (HTTP Meta tags & OpenGraph)
[params.meta]
  description = "Hobby nerd"
  keywords = "Coniass,infrastructure, sysadmin, architect"
  images = [
    "/images/profile.jpg"
  ]

## Profile Configurations
[params.profile]
  portrait = "/images/portrait-default.png"
  firstname = "Tim aka"
  lastname = "Coniass"
  title = "Hobby nerd / IT Apprentice"
  bio = """Oh, here we go again with another tech enthusiast – and that’s me, Coniass or Tim! I've got some decent tech skills and a thirst for networking knowledge, but let’s not get too carried away with grandiose claims.

With some experience in IT under my belt, I’ve managed to troubleshoot many issues successfully. Setting up networks wasn’t a cakewalk, but I made it through without causing too much chaos. As for being a tech god, well, I might need more certifications and experience for that title.

I also have an obsession with microelectronics. You could say I’m a bit of a circuit board maniac, dabbling in electronics like a somewhat eccentric scientist. My friends humor me and become brave testers of my latest creations.

I get a real thrill out of configuring networks and ensuring smooth data transmission. Troubleshooting network issues gives me a sense of accomplishment like no other. My friends are always impressed with my ability to navigate through network challenges.

I must admit, there have been a few “exciting” moments when I nearly accidentally shocked myself. But hey, what’s life without a little shock therapy, right? (Please don’t try this at home, folks!)

If you’re looking for an IT enthusiast with a genuine love for networking, a sprinkle of quirkiness, and a talent for creating electrifying network setups, then I’m the perfect fit for the job. I’ll be your “network magician,” making sure the data flows seamlessly and the connections remain strong. No voltage mishaps on the networking front!

And there you have it – the tech-savvy, networking-loving, microelectronics-obsessed Coniass, ready to take on the IT world with a touch of self-satire!
"""
[params.contacts]
  email = "	contact@coniass.com"
  twitter = "Coniass_"
  keybase = "Coniass"
  github = "Coniass"

## Actions Configurations
[[params.actions]]
  name = "Review My CV"
  url = "https://coniass.com/content/cv.pdf"
  
## Footer Configurations
[params.footer]
  copyright = "© 2019-2020 Byungjin Park. [CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/)."
  poweredBy = true

[privacy]
  [privacy.googleAnalytics]
    disable = false
    # Make the users’ IP addresses are anonymized within Google Analytics
    anonymizeIP = true
    # Make the GA templates respect the “Do Not Track” HTTP header
    respectDoNotTrack = true
    # Disable the use of Cookies and use Session Storage to Store the GA Client ID
    useSessionStorage = true
	
	
